### PR TITLE
Add team project template

### PR DESCRIPTION
**Pull request by j-lum**
I've included a set of sample documentation in github flavored markdown following AB-3's format as closely as possible for students to follow. 

If everything is good I'll squash and merge.

### CODE REVIEW

**Comment by damithc** [comment]
Any changes needed to existing tutorial files? If yes, can do in this PR itself?
Also, should we add the GitHub actions stuff to this PR?

**Comment by j-lum** [comment]
Actually I think we should pull the tutorials out of this branch. The github actions are already in this PR's second commit.

**Comment by damithc** [comment]
We should add some documentation on how to set up GitHub actions, right?

**Comment by j-lum** [comment]
Actually they don't have to do anything to get github actions working, github picks up on the workflow file automatically.

**Comment by damithc** [comment]
> Actually they don't have to do anything to get github actions working, github picks up on the workflow file automatically.

Oh? cool.

**Comment by j-lum** [comment]
> 
> 
> > Actually they don't have to do anything to get github actions working, github picks up on the workflow file automatically.
> 
> Oh? cool.

This way we can skip the whole Travis part of the tutorial. 
If it's good I'll merge it and look into how we can configure an action to automatically generate and publish the jars for their v1.3 and v1.4 submission.

**Comment by damithc** [comment]
Go ahead and merge. I'll tweak the docs later.

**Comment by damithc** [comment]
@j-lum I've pushed some tweaks to doc templates. Some things I need your help with, in order of priority:
* In the build.gradle -> java.duke should be seedu.duke?
* CS2113 students haven't learned Gradle yet. We need to repurpose the previous Gradle tutorial for this branch.
* Can we also add I/O redirection tests to CI? As CS2113 students will be doing a text UI, they will continue to use I/O redirection testing. See if you can adapt it from AB1 (which uses Gradle for I/O testing) to work with GitHub actions. If can, put a dummy version of it into the project (i.e., empty input.txt and EXPECTED.txt)
* Can update the CI config to run on all three platforms?

**Comment by damithc** [comment]
> @j-lum I've pushed some tweaks to doc templates. Some things I need your help with, in order of priority:

@j-lum this one is a bit urgent as I need to release the tP template in two days. If no time to do all, can do the higher priority ones.

**Pull request merged**
