### PR TITLE
Add GitHub Actions for continuous integration

### PR DESCRIPTION
**Pull request by j-lum**
As the process of setting up Travis is a cause of friction for many
students, let's adopt GitHub Actions for our CI tool.

### CODE REVIEW

**Comment by damithc** [comment]
Just curious.: can it be run on multiple platforms as well?

**Comment by j-lum** [comment]
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on

Has support for Windows and Mac as well which is pretty great.

**Comment by damithc** [comment]
I meant, can we set it up to test on all three platforms?

**Comment by j-lum** [comment]
I forced-push a version that tests on all three platforms. 
Sample output is available here https://github.com/j-lum/duke/runs/422500194 but windows seems really slow.

**Comment by damithc** [comment]
Should we make the other changes (i.e., minimal JUnit, checkstyle) in this branch as well? After that, I'll simply merge this branch in the CS2113 fork and give that to students as the starter repo for their tP. After observing how that goes, we can decide how to incorporate this feature into Duke usages in both CS2103 (in iP) and CS2113 (in tP).

**Comment by j-lum** [comment]
I'll have a separate branch that has a complete project ready for deployment soon.

**Comment by damithc** [comment]
Thx. We need it to be ready within a week.

**Comment by damithc** [comment]
@j-lum any updates?

**Comment by j-lum** [comment]
Closing this in favor of #45 which is a more complete template.

**Pull request closed without merging**
