### PR TITLE
Remove Typo in Tutorial 4

### LINKED ISSUE #40: JavaFxTutorial 4: Typo in code example
There is an additional `@Override` annotation in `tutorials/javaFxTutorialPart4.md` at line 175.

### PR DESCRIPTION
**Pull request by jiachen247**
Resolves #40 
Remove unnecessary '@Override' at the start of the code example in tutorial 4 markdown.

### CODE REVIEW

**Comment by j-lum** [comment]
Thanks for the PR. Consider changing the commit message to have proper capitalization and 'extra' to 'unnecessary' for clarity.

**Comment by jiachen247** [comment]
made the requested changes! @j-lum

**Comment by j-lum** [comment]
Merging and closing!

**Comment by damithc** [comment]
Thanks for the contribution @jiachen247

**Pull request merged**
